# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  # Define your environment-specific variables here
  buildConfiguration: 'development'
  # Add any other variables you need for deployment, like connection strings, etc.

steps:
- script: |
    npm install -g @angular/cli
    npm install
    ng build-development
  displayName: 'Build Angular App'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'
